POST http://localhost:3002/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0YTJlZTkwZWY5ODJhMGM5ZTA3ODVjZCIsImlhdCI6MTY4ODU0MjQ0OCwiZXhwIjoxNjg4NTQ2MDQ4fQ.fLvHGl4nV4fgD7Q0WJKbeIixuISuuL3_Ptv5QLPNN1A

{
    "title": "another one",
    "author": "abc",
    "url": "abc", 
    "likes": 6,
    "user": "64a2ee7eef982a0c9e0785c9"
}